"""empty message

Revision ID: 95b1707da9b6
Revises: 
Create Date: 2020-01-09 19:47:51.685417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b1707da9b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_name', sa.String(length=21), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('n_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('note_title', sa.String(length=255), nullable=True),
    sa.Column('note_labels', sa.String(length=255), nullable=True),
    sa.Column('note_instructions', sa.TEXT(), nullable=True),
    sa.Column('note_content', sa.TEXT(), nullable=True),
    sa.Column('creation_time', sa.String(length=255), nullable=True),
    sa.Column('click_number', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('n_id')
    )
    op.create_table('top_category',
    sa.Column('uuid', sa.String(length=36), nullable=True),
    sa.Column('top_category_name', sa.String(length=255), nullable=False),
    sa.Column('sec_category', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('top_category_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('top_category')
    op.drop_table('notes')
    op.drop_table('admin')
    # ### end Alembic commands ###
